name: test examples

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    if: github.event.head_commit && !contains(github.event.head_commit.message, 'nogha')
    strategy:
      fail-fast: false
      matrix:
        include:
          - {python: '3.13'}
          - {python: '3.12'}
          - {name: PyPy, python: 'pypy-3.11', tox: pypy3.11}

    steps:
      - uses: actions/checkout@v4
    
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        id: setup-python
        with:
          python-version-file: pyproject.toml
  
      - name: cargo version
        run: cargo --version
  
      # Ubuntu system dependencies for Postgres
      - name: remove old postgres
        run: sudo apt remove -y postgres*
    
