name: release

on:
  workflow_dispatch:
    inputs:
      archs:
        description: 'JSON array of architectures'
        required: true

permissions:
  contents: write
  actions: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    environment: release

    strategy:
      fail-fast: false
      matrix:
        # arch: ${{ fromJSON('[''ppc64'']') }} # fails
        arch: ${{ fromJSON("['ppc64']") }}

    steps:
      - name: Show selected target
        shell: bash
        run: |
          echo "ARCH=${{ matrix.arch }}
